# Generated by Django 4.2.4 on 2023-08-11 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="mobile_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+8801XXXXXX'. Up to 14 digits allowed.",
                        regex="^(?:\\+88|88|+967|967)?(01[3-9]\\d{8})$",
                    )
                ],
            ),
        ),
    ]
