# Generated by Django 4.2.4 on 2023-08-11 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_users_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="mobile_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+9677XXXXXX'. Up to 14 digits allowed.",
                        regex="^(?:\\+88|88|+967|967)?(70[3-9]\\d{8}|71[3-9]\\d{8}|73[3-9]\\d{8}|77[3-9]\\d{8}|01[3-9]\\d{8})$",
                    )
                ],
            ),
        ),
    ]
