# Generated by Django 4.2.4 on 2023-08-11 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_farm_rename_users_farmer_schedule_detail_farm_farmer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmer",
            options={"verbose_name": "Farmer", "verbose_name_plural": "Farmers"},
        ),
    ]
