# Generated by Django 4.2.4 on 2023-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_farm_area_farm_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="crop_grown",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
