# Generated by Django 4.2.4 on 2023-08-11 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_farm_latitude_farm_longitude_alter_farm_crop_grown"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="schedule_detail",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_detail",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule_detail",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AddField(
            model_name="schedule_detail",
            name="types",
            field=models.ManyToManyField(to="app.type"),
        ),
    ]
