# Generated by Django 4.2.4 on 2023-08-11 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_type_schedule_detail_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="The_highest_appropriate_temperature",
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="The_lowest_appropriate_temperature",
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="category",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="produce_images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="nutrients",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="origin",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9
            ),
            preserve_default=False,
        ),
    ]
