# Generated by Django 4.2.4 on 2023-08-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_type_the_highest_appropriate_temperature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="effect_of_heat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="effect_of_humidity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="effect_of_illumination",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="humidity_highest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="humidity_lowest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="illumination_highest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="illumination_lowest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="type",
            name="nutrients",
            field=models.TextField(auto_created=True, blank=True, null=True),
        ),
    ]
