# Generated by Django 4.2.4 on 2023-08-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_type_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="humidity_highest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="humidity_lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="illumination_highest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="illumination_lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fruits", "Fruits"),
                    ("Veggies", "Veggies"),
                    ("g", "grams"),
                    ("L", "litres"),
                    ("mL", "millitres"),
                ],
                help_text="Select type:",
                max_length=50,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
