# Generated by Django 4.2.4 on 2023-08-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_type_humidity_highest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="type",
            old_name="humidity_highest",
            new_name="atmospheric_pressure_highest",
        ),
        migrations.RenameField(
            model_name="type",
            old_name="humidity_lowest",
            new_name="atmospheric_pressure_lowest",
        ),
        migrations.RenameField(
            model_name="type",
            old_name="effect_of_humidity",
            new_name="effect_of_atmospheric_pressure",
        ),
        migrations.AddField(
            model_name="type",
            name="effect_of_soil_humidity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="effect_of_weather_humidity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="type",
            name="humidity_soil_highest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="humidity_soil_lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="humidity_weather_highest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="humidity_weather_lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
    ]
