# Generated by Django 4.2.4 on 2023-08-11 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0014_rename_humidity_highest_type_atmospheric_pressure_highest_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Type",
            new_name="Category",
        ),
    ]
