# Generated by Django 4.2.4 on 2023-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_rename_type_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="token",
        ),
        migrations.AddField(
            model_name="farmer",
            name="passowrd",
            field=models.CharField(
                blank=True,
                help_text="passowrd for authentication",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="passowrd",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Fruits", "Fruits"), ("Veggies", "Veggies")],
                help_text="Select type:",
                max_length=50,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
