# Generated by Django 4.2.4 on 2023-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_farmer_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="business",
            field=models.CharField(
                blank=True,
                choices=[
                    ("المالك", "المالك"),
                    ("تقني", "تقني"),
                    ("المدير", "المدير"),
                    ("مختبر", "مختبر"),
                    ("خبير ", "خبير"),
                ],
                help_text="Select your business type:",
                max_length=50,
                null=True,
                verbose_name="Business",
            ),
        ),
    ]
