# Generated by Django 4.2.3 on 2023-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_farmer_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="mobile_number",
            field=models.CharField(max_length=20),
        ),
    ]
