# Generated by Django 4.2.3 on 2023-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_schedule_detail_fertiliser_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="farm", name="sowing_date",),
        migrations.AlterField(
            model_name="farm",
            name="established_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
