# Generated by Django 4.2.3 on 2023-08-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_farm_sowing_date_alter_farm_established_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="village",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
