# Generated by Django 4.2.3 on 2023-08-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_farm_description_alter_farm_farmer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule_detail",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.category",
            ),
        ),
    ]
