# Generated by Django 4.2.3 on 2023-08-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0026_rename_the_highest_appropriate_temperature_schedule_detail_the_appropriate_temperature_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="effect_water_tomperatatur",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="water_tomperatatur_ighest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="water_tomperatatur_lowest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="schedule_detail",
            name="water_tomperatatur",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
    ]
